[package]
name = "showerthoughts"
version = "0.3.0"
edition = "2018"
authors = ["Ivan Mondragon <imondrag@umich.edu>"]
license = "MIT"

[dependencies]
reqwest = "0.9.9"
app_dirs = "1.2.1"
preferences = "1.1.0"
rand = "0.6.5"
serde = "1.0.87"
serde_derive = "1.0.87"
serde_json = "1.0.38"
bincode = "1.1.1"
lazy_static = "1.2.0"
log = "0.4.6"
pretty_env_logger = "0.3.0"

[profile.release]
opt-level = 3
lto = true
