[package]
name = "showerthoughts"
version = "0.1.0"
edition = "2018"
authors = ["Ivan Mondragon <imondrag@umich.edu>"]

[dependencies]
reqwest = "*"
app_dirs = "*"
preferences = "*"
rand = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
bincode = "*"
lazy_static = "*"
