[package]
name = "showerthoughts"
version = "0.3.0"
edition = "2018"
authors = ["Ivan Mondragon <imondrag@umich.edu>"]
license = "MIT"

[dependencies]
reqwest = "0.9.5"
app_dirs = "1.2.1"
preferences = "1.1.0"
rand = "0.6.1"
serde = "1.0.82"
serde_derive = "1.0.82"
serde_json = "1.0.33"
bincode = "1.0.1"
lazy_static = "1.2.0"

[profile.release]
opt-level = 3
lto = true
